# Generated by Django 4.1.7 on 2023-07-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='staff_img',
            new_name='user_img',
        ),
    ]
