# Generated by Django 4.1.7 on 2023-07-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('stream_id', models.CharField(max_length=255)),
                ('stream_url', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('video_path', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('excel_path', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysisObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('label', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('total_count_in', models.IntegerField(default=0)),
                ('total_count_out', models.IntegerField(default=0)),
                ('video_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.videoanalysismodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('total_count_in', models.IntegerField(default=0)),
                ('total_count_out', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.stream'),
        ),
    ]
