# Generated by Django 3.2.20 on 2023-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysismodel',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
