# Generated by Django 3.2 on 2023-07-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_image_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('total_count_in', models.IntegerField(default=0)),
                ('total_count_out', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.image')),
            ],
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
