# Generated by Django 3.2.20 on 2023-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_videoanalysismodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysismodel',
            name='short_video_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
