# Generated by Django 3.2 on 2023-07-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20230706_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidoe_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('vidoe_path', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('excel_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysisObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('total_count_in', models.IntegerField(default=0)),
                ('total_count_out', models.IntegerField(default=0)),
                ('video_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.videoanalysismodel')),
            ],
        ),
    ]
