# Generated by Django 3.2 on 2023-07-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_videoanalysismodel_videoanalysisobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoanalysismodel',
            old_name='vidoe_name',
            new_name='video_name',
        ),
        migrations.RenameField(
            model_name='videoanalysismodel',
            old_name='vidoe_path',
            new_name='video_path',
        ),
        migrations.AlterField(
            model_name='videoanalysismodel',
            name='excel_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
