# Generated by Django 3.2 on 2023-07-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20230708_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysismodel',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
