# Generated by Django 3.2 on 2023-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_videoanalysismodel_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysisobject',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
