# Generated by Django 3.2.16 on 2023-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
